<?php

namespace Workbench\App\Enum;

enum Department: string
{
    case Ain = '01';
    case Aisne = '02';
    case Allier = '03';
    case AlpesDeHauteProvence = '04';
    case HautesAlpes = '05';
    case AlpesMaritimes = '06';
    case Ardeche = '07';
    case Ardennes = '08';
    case Ariege = '09';
    case Aube = '10';
    case Aude = '11';
    case Aveyron = '12';
    case BouchesDuRhone = '13';
    case Calvados = '14';
    case Cantal = '15';
    case Charente = '16';
    case CharenteMaritime = '17';
    case Cher = '18';
    case Correze = '19';
    case CorseDuSud = '2A';
    case CorseDuNord = '2B';
    case CoteDOr = '21';
    case CotesDArmor = '22';
    case Creuse = '23';
    case Dordogne = '24';
    case Doubs = '25';
    case Drome = '26';
    case Eure = '27';
    case EureEtLoir = '28';
    case Finistere = '29';
    case Gard = '30';
    case HauteGaronne = '31';
    case Gers = '32';
    case Gironde = '33';
    case Herault = '34';
    case IlleEtVilaine = '35';
    case Indre = '36';
    case IndreEtLoire = '37';
    case Isere = '38';
    case Jura = '39';
    case Landes = '40';
    case LoirEtCher = '41';
    case Loire = '42';
    case HauteLoire = '43';
    case LoireAtlantique = '44';
    case Loiret = '45';
    case Lot = '46';
    case LotEtGaronne = '47';
    case Lozere = '48';
    case MaineEtLoire = '49';
    case Manche = '50';
    case Marne = '51';
    case HauteMarne = '52';
    case Mayenne = '53';
    case MeurtheEtMoselle = '54';
    case Meuse = '55';
    case Morbihan = '56';
    case Moselle = '57';
    case Nievre = '58';
    case Nord = '59';
    case Oise = '60';
    case Orne = '61';
    case PasDeCalais = '62';
    case PuyDeDome = '63';
    case PyreneesAtlantiques = '64';
    case HautesPyrenees = '65';
    case PyreneesOrientales = '66';
    case BasRhin = '67';
    case HautRhin = '68';
    case Rhone = '69';
    case HauteSaone = '70';
    case SaoneEtLoire = '71';
    case Sarthe = '72';
    case Savoie = '73';
    case HauteSavoie = '74';
    case Paris = '75';
    case SeineMaritime = '76';
    case SeineEtMarne = '77';
    case Yvelines = '78';
    case DeuxSevres = '79';
    case Somme = '80';
    case Tarn = '81';
    case TarnEtGaronne = '82';
    case Var = '83';
    case Vaucluse = '84';
    case Vendee = '85';
    case Vienne = '86';
    case HauteVienne = '87';
    case Vosges = '88';
    case Yonne = '89';
    case TerritoireDeBelfort = '90';
    case Essonne = '91';
    case HautsDeSeine = '92';
    case SeineSaintDenis = '93';
    case ValDeMarne = '94';
    case ValDOise = '95';
    case Guadeloupe = '971';
    case Martinique = '972';
    case Guyane = '973';
    case Reunion = '974';
    case Mayotte = '976';

    public static function fromName(string $departmentName): Department
    {
        $firstUppercaseDepartmentName = ucfirst($departmentName);

        return match ($firstUppercaseDepartmentName) {
            'Ain' => self::Ain,
            'Aisne' => self::Aisne,
            'Allier' => self::Allier,
            'Alpes-de-Haute-Provence' => self::AlpesDeHauteProvence,
            'Hautes-Alpes' => self::HautesAlpes,
            'Alpes-Maritimes' => self::AlpesMaritimes,
            'Ardèche' => self::Ardeche,
            'Ardennes' => self::Ardennes,
            'Ariège' => self::Ariege,
            'Aube' => self::Aube,
            'Aude' => self::Aude,
            'Aveyron' => self::Aveyron,
            'Bouches-du-Rhône' => self::BouchesDuRhone,
            'Calvados' => self::Calvados,
            'Cantal' => self::Cantal,
            'Charente' => self::Charente,
            'Charente-Maritime' => self::CharenteMaritime,
            'Cher' => self::Cher,
            'Corrèze' => self::Correze,
            'Corse-du-Sud' => self::CorseDuSud,
            'Haute-Corse' => self::CorseDuNord,
            "Côte-d'Or" => self::CoteDOr,
            "Côtes-d'Armor" => self::CotesDArmor,
            'Creuse' => self::Creuse,
            'Dordogne' => self::Dordogne,
            'Doubs' => self::Doubs,
            'Drôme' => self::Drome,
            'Eure' => self::Eure,
            'Eure-et-Loir' => self::EureEtLoir,
            'Finistère' => self::Finistere,
            'Gard' => self::Gard,
            'Haute-Garonne' => self::HauteGaronne,
            'Gers' => self::Gers,
            'Gironde' => self::Gironde,
            'Hérault' => self::Herault,
            'Ille-et-Vilaine' => self::IlleEtVilaine,
            'Indre' => self::Indre,
            'Indre-et-Loire' => self::IndreEtLoire,
            'Isère' => self::Isere,
            'Jura' => self::Jura,
            'Landes' => self::Landes,
            'Loir-et-Cher' => self::LoirEtCher,
            'Loire' => self::Loire,
            'Haute-Loire' => self::HauteLoire,
            'Loire-Atlantique' => self::LoireAtlantique,
            'Loiret' => self::Loiret,
            'Lot' => self::Lot,
            'Lot-et-Garonne' => self::LotEtGaronne,
            'Lozère' => self::Lozere,
            'Maine-et-Loire' => self::MaineEtLoire,
            'Manche' => self::Manche,
            'Marne' => self::Marne,
            'Haute-Marne' => self::HauteMarne,
            'Mayenne' => self::Mayenne,
            'Meurthe-et-Moselle' => self::MeurtheEtMoselle,
            'Meuse' => self::Meuse,
            'Morbihan' => self::Morbihan,
            'Moselle' => self::Moselle,
            'Nièvre' => self::Nievre,
            'Nord' => self::Nord,
            'Oise' => self::Oise,
            'Orne' => self::Orne,
            'Pas-de-Calais' => self::PasDeCalais,
            'Puy-de-Dôme' => self::PuyDeDome,
            'Pyrénées-Atlantiques' => self::PyreneesAtlantiques,
            'Hautes-Pyrénées' => self::HautesPyrenees,
            'Pyrénées-Orientales' => self::PyreneesOrientales,
            'Bas-Rhin' => self::BasRhin,
            'Haut-Rhin' => self::HautRhin,
            'Rhône' => self::Rhone,
            'Haute-Saône' => self::HauteSaone,
            'Saône-et-Loire' => self::SaoneEtLoire,
            'Sarthe' => self::Sarthe,
            'Savoie' => self::Savoie,
            'Haute-Savoie' => self::HauteSavoie,
            'Paris' => self::Paris,
            'Seine-Maritime' => self::SeineMaritime,
            'Seine-et-Marne' => self::SeineEtMarne,
            'Yvelines' => self::Yvelines,
            'Deux-Sèvres' => self::DeuxSevres,
            'Somme' => self::Somme,
            'Tarn' => self::Tarn,
            'Tarn-et-Garonne' => self::TarnEtGaronne,
            'Var' => self::Var,
            'Vaucluse' => self::Vaucluse,
            'Vendée' => self::Vendee,
            'Vienne' => self::Vienne,
            'Haute-Vienne' => self::HauteVienne,
            'Vosges' => self::Vosges,
            'Yonne' => self::Yonne,
            'Territoire de Belfort' => self::TerritoireDeBelfort,
            'Essonne' => self::Essonne,
            'Hauts-de-Seine' => self::HautsDeSeine,
            'Seine-Saint-Denis' => self::SeineSaintDenis,
            'Val-de-Marne' => self::ValDeMarne,
            "Val-d'Oise" => self::ValDOise,
            'Guadeloupe' => self::Guadeloupe,
            'Martinique' => self::Martinique,
            'Guyane' => self::Guyane,
            'La Réunion' => self::Reunion,
            'Mayotte' => self::Mayotte,
            default => throw new \InvalidArgumentException('Invalid department name: '.$departmentName),
        };
    }

    public function region(): Region
    {
        return match ($this) {
            self::Ain => Region::AuvergneRhoneAlpes,
            self::Aisne => Region::HautsDeFrance,
            self::Allier => Region::AuvergneRhoneAlpes,
            self::AlpesDeHauteProvence => Region::ProvenceAlpesCoteDazur,
            self::HautesAlpes => Region::ProvenceAlpesCoteDazur,
            self::AlpesMaritimes => Region::ProvenceAlpesCoteDazur,
            self::Ardeche => Region::AuvergneRhoneAlpes,
            self::Ardennes => Region::GrandEst,
            self::Ariege => Region::Occitanie,
            self::Aube => Region::GrandEst,
            self::Aude => Region::Occitanie,
            self::Aveyron => Region::Occitanie,
            self::BouchesDuRhone => Region::ProvenceAlpesCoteDazur,
            self::Calvados => Region::Normandie,
            self::Cantal => Region::AuvergneRhoneAlpes,
            self::Charente => Region::NouvelleAquitaine,
            self::CharenteMaritime => Region::NouvelleAquitaine,
            self::Cher => Region::CentreValDeLoire,
            self::Correze => Region::NouvelleAquitaine,
            self::CorseDuSud => Region::Corse,
            self::CorseDuNord => Region::Corse,
            self::CoteDOr => Region::BourgogneFrancheComte,
            self::CotesDArmor => Region::Bretagne,
            self::Creuse => Region::NouvelleAquitaine,
            self::Dordogne => Region::NouvelleAquitaine,
            self::Doubs => Region::BourgogneFrancheComte,
            self::Drome => Region::AuvergneRhoneAlpes,
            self::Eure => Region::Normandie,
            self::EureEtLoir => Region::CentreValDeLoire,
            self::Finistere => Region::Bretagne,
            self::Gard => Region::Occitanie,
            self::HauteGaronne => Region::Occitanie,
            self::Gers => Region::Occitanie,
            self::Gironde => Region::NouvelleAquitaine,
            self::Herault => Region::Occitanie,
            self::IlleEtVilaine => Region::Bretagne,
            self::Indre => Region::CentreValDeLoire,
            self::IndreEtLoire => Region::CentreValDeLoire,
            self::Isere => Region::AuvergneRhoneAlpes,
            self::Jura => Region::BourgogneFrancheComte,
            self::Landes => Region::NouvelleAquitaine,
            self::LoirEtCher => Region::CentreValDeLoire,
            self::Loire => Region::AuvergneRhoneAlpes,
            self::HauteLoire => Region::AuvergneRhoneAlpes,
            self::LoireAtlantique => Region::PaysDeLaLoire,
            self::Loiret => Region::CentreValDeLoire,
            self::Lot => Region::Occitanie,
            self::LotEtGaronne => Region::NouvelleAquitaine,
            self::Lozere => Region::Occitanie,
            self::MaineEtLoire => Region::PaysDeLaLoire,
            self::Manche => Region::Normandie,
            self::Marne => Region::GrandEst,
            self::HauteMarne => Region::GrandEst,
            self::Mayenne => Region::PaysDeLaLoire,
            self::MeurtheEtMoselle => Region::GrandEst,
            self::Meuse => Region::GrandEst,
            self::Morbihan => Region::Bretagne,
            self::Moselle => Region::GrandEst,
            self::Nievre => Region::BourgogneFrancheComte,
            self::Nord => Region::HautsDeFrance,
            self::Oise => Region::HautsDeFrance,
            self::Orne => Region::Normandie,
            self::PasDeCalais => Region::HautsDeFrance,
            self::PuyDeDome => Region::AuvergneRhoneAlpes,
            self::PyreneesAtlantiques => Region::NouvelleAquitaine,
            self::HautesPyrenees => Region::Occitanie,
            self::PyreneesOrientales => Region::Occitanie,
            self::BasRhin => Region::GrandEst,
            self::HautRhin => Region::GrandEst,
            self::Rhone => Region::AuvergneRhoneAlpes,
            self::HauteSaone => Region::BourgogneFrancheComte,
            self::SaoneEtLoire => Region::BourgogneFrancheComte,
            self::Sarthe => Region::PaysDeLaLoire,
            self::Savoie => Region::AuvergneRhoneAlpes,
            self::HauteSavoie => Region::AuvergneRhoneAlpes,
            self::Paris => Region::IleDeFrance,
            self::SeineMaritime => Region::Normandie,
            self::SeineEtMarne => Region::IleDeFrance,
            self::Yvelines => Region::IleDeFrance,
            self::DeuxSevres => Region::NouvelleAquitaine,
            self::Somme => Region::HautsDeFrance,
            self::Tarn => Region::Occitanie,
            self::TarnEtGaronne => Region::Occitanie,
            self::Var => Region::ProvenceAlpesCoteDazur,
            self::Vaucluse => Region::ProvenceAlpesCoteDazur,
            self::Vendee => Region::PaysDeLaLoire,
            self::Vienne => Region::NouvelleAquitaine,
            self::HauteVienne => Region::NouvelleAquitaine,
            self::Vosges => Region::GrandEst,
            self::Yonne => Region::BourgogneFrancheComte,
            self::TerritoireDeBelfort => Region::BourgogneFrancheComte,
            self::Essonne => Region::IleDeFrance,
            self::HautsDeSeine => Region::IleDeFrance,
            self::SeineSaintDenis => Region::IleDeFrance,
            self::ValDeMarne => Region::IleDeFrance,
            self::ValDOise => Region::IleDeFrance,
            self::Guadeloupe => Region::DomTom,
            self::Martinique => Region::DomTom,
            self::Guyane => Region::DomTom,
            self::Reunion => Region::DomTom,
            self::Mayotte => Region::DomTom,
        };
    }

    public function translationKey(): string
    {
        return 'department.'.$this->value;
    }
}
